AWSTemplateFormatVersion: "2010-09-09"
Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bkt-aman-elitebook
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false  # Allow public ACLs
        IgnorePublicAcls: false  # Allow public ACLs
        BlockPublicPolicy: false  # Allow public policies
        RestrictPublicBuckets: false  # Do not restrict public access

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "s3:GetObject"
            Resource: arn:aws:s3:::my-bucket-aman-elitebook/*
            Principal: "*"

Outputs:
  WebsiteURL:
    Description: "URL of the static website"
    Value: !Sub "http://${StaticWebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"

