name: Deploy Static Website to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # The AWS Access Key ID from GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # The AWS Secret Access Key from GitHub Secrets
          aws-region: us-east-1  # AWS Region where the S3 bucket is located

      - name: Sync website files to S3
        run: |
          aws s3 sync . s3://my-bkt-aman-elitebook --exclude ".git/*"  # Replace with your S3 bucket name

